/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Image from "next/image";
import Link from 'next/link';
import { Inter } from "@next/font/google";
import { FaFacebookF, FaInstagram, FaLinkedinIn } from "react-icons/fa";
import { BsArrowRightCircle } from "react-icons/bs";
import styles from "../styles/Home.module.css";
import BackSpaceAnimate from "../src/components/BackSpaceAnimate";
import SpaceMan from "../src/components/SpaceMan";
import { Container, Nav, Navbar } from "react-bootstrap";

const inter = Inter({ subsets: ["latin"] });


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link><link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;400;500;600;700;900&display=swap" rel="stylesheet"></link>
      </Head>

      <section className="port-background">
        <Navbar expand="lg">
          <Container>
            <Navbar.Brand href="/" style={{ margin: '0px' }}>
              <img src="/AnupSolanki.svg" width='100%' height='50%' alt="" />
            </Navbar.Brand>
            <Navbar.Toggle aria-controls="basic-navbar-nav" />
            <Navbar.Collapse
              className="justify-content-end"
              id="basic-navbar-nav"
            >
              <Nav className="mb-4">
                <li className="nav-item">
                  <div className="tabs col">
                    <ul>
                      <li> <Link href='/'> Home </Link></li>
                      <li> <Link href='/skills'> Skills </Link></li>
                      <li> <Link href='/projects'> Projects </Link></li>
                    </ul>
                  </div>
                </li>
              </Nav>
              <Nav className="mb-4">
                <li className="nav-item">
                  <div className="socials navbar-nav mr-auto">
                    <ul>
                      <li className="linked">
                        <FaLinkedinIn />
                      </li>
                      <li className="insta">
                        <FaInstagram />
                      </li>
                      <li className="facebook">
                        <FaFacebookF />
                      </li>
                    </ul>
                  </div>
                </li>
              </Nav>
              <Nav className="mb-4">
                <li className="nav-item">
                  <div className="action-btn navbar-nav mr-auto">
                    <button> Let's Connect</button>
                  </div>
                </li>
              </Nav>
            </Navbar.Collapse>
          </Container>
        </Navbar>
        <div>
          {/* <div className="space-back">
          <BackSpaceAnimate />
        </div> */}

          <div className="port-intro text-light container">
            <div className="space-man col">
              <SpaceMan />
            </div>
            <div className="col">
              <div className="row">
                <span className="intro-title">
                  <h4>Welcome to my Portfolio</h4>
                </span>
              </div>
              <div className="row">
                <div className="cont">
                  <h3>Hi! my Name is Anup.</h3>
                  <div className="typewriter">
                    <h3 className="typing-erase">Web Developer!</h3>
                  </div>
                </div>
              </div>
              <div className="row">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum dolor cumque impedit similique sit suscipit repudiandae sint minus, amet quisquam aut error, sed, placeat sequi.</p>
              </div>
              <div className="row connect-row">
                <h5>Let's Connect <BsArrowRightCircle /></h5>
              </div>
            </div>

          </div>

        </div>
      </section>
    </>
  );
}
